#!/bin/sh
#
# Script para ver funcionamiento de if else

if [ $# -eq 0 ]
then
echo "$0: Ingresar numero"
exit 1
fi

if test $1 -gt 0 
then
echo "El numero es positivo"
else
echo "El numero es negativo"
fi

