#!/bin/sh
#
# Script para demostrar el comando while

if [ $# -eq 0 ]
then
echo "Error - Debe usar un argumento"
echo "syntax: $0 numero"
echo "El script mostrara la tabla de multiplicacion para el numero"
exit 1
fi
n=$1
i=1
while [ $i -le 10 ]
do
echo "$n * $i = `expr $n \* $i`"
i=`expr $i + 1`
done 
